### ISSUE TITLE
Obsoletion notice: 'GO:0051821 dissemination or transmission of organism from other organism involved in symbiotic interaction' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#100]
Dear all, 

The proposal has been made to obsolete 'GO:0051821 dissemination or transmission of organism from other organism involved in symbiotic interaction' and children. 
- GO:0051821 dissemination or transmission of organism from other organism involved in symbiotic interaction -> 0 EXP 
-  GO:0051822 dissemination or transmission of organism from other organism by vector involved in symbiotic interaction-> 0 EXP  
- GO:0044007 dissemination or transmission of symbiont from host > 0 EXP  
- GO:0044008 dissemination or transmission of symbiont from host by vector -> 2 EXP 
- GO:0019089 transmission of virus -> 5 annotations
- GO:0044009  viral transmission by vector  -> 0 annotations

The reason for obsoletion is that those terms do not represent specific processes. If possible the genes should be annotated to more specific terms. 

Annotation review requests are here: 
- GO:0044008   https://docs.google.com/spreadsheets/d/1qFs7XoGqMhUeL-qKY0mEqlb-0n2KmtoRnzZcbbDI6ts/edit#gid=0
@Achchuthan @sandyl27 

- GO:0019089 https://docs.google.com/spreadsheets/d/1VQlN_F0IKcqL7gTG0tw9zFbfnXZ_fdctnTtoZvpSxVg/edit#gid=0
@pgarmiri @RLovering 

There are 3 InterPro domains with mapping to GO:0019089 transmission of virus

InterPro:IPR007935
InterPro:IPR004917
InterPro:IPR007982
@happy-lorna 

The terms are not present in any subsets. 

Any comment may be added to the ticket:

https://github.com/geneontology/go-ontology/issues/18601.

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on February 10th, 2020. Unless objections are received by February 10th, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by typhainepl** [comment]
I have removed the GO terms from the InterPro entries.
