### ISSUE TITLE
Obsolete GO:0000903 regulation of cell shape during vegetative growth phase

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#15]
Dear all,

The proposal has been made to obsolete GO:0000903 regulation of cell shape during vegetative growth phase. The reason for obsoletion is that the

There are 3 experimental annotations to this term by SGD (2 EXP) and PomBase (1 EXP).
There are no InterPro2GO mappings to this term and the term is not in any subsets.
Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/16285
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on September 4th, 2018. Unless objections are received by September 4th, 2018, we will assume that you agree to this change.

Thanks, Pascale

**Comment by srengel** [comment]
i have changed the SGD annotations to regulation of cell shape GO:0008360 w/col16 happens_during(GO:0072690) single-celled organism vegetative growth phase
