### ISSUE TITLE
Obsoletion notice GO:0031659 positive regulation of cyclin-dependent protein serine/threonine kinase activity involved in G1/S transition of mitotic cell cycle

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#16]
The proposal has been made to obsolete GO:0031659 positive regulation of cyclin-dependent protein serine/threonine kinase activity involved in G1/S transition of mitotic cell cycle. The reason for obsoletion is that this term can be captured as a GO-CAM model.

There are 9 manual annotation (PomBase; UniProt BHF); no InterPro mappings; the term is not present in any slims. Annotations are here: https://docs.google.com/spreadsheets/d/1ARpUTcTIj8BrMa57HGC0RCjLSaFLHgI1hTgkLkZ_oys/edit#gid=0

Comments can be added to the ticket: https://github.com/geneontology/go-ontology/issues/16312

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on September 6, 2018. Unless objections are received by September 6, 2018, we will assume that you agree to this change.

Thanks,

Pascale

**Comment by pgaudet** [comment]
Slight modification to the proposal: The proposal is to obsolete the trio: 


• GO:0031657 regulation of cyclin-dependent protein serine/threonine kinase activity involved in G1/S transition of mitotic cell cycle
	• GO:0031658 negative regulation of cyclin-dependent protein serine/threonine kinase activity involved in G1/S transition of mitotic cell cycle
	• GO:0031659 positive regulation of cyclin-dependent protein serine/threonine kinase activity involved in G1/S transition of mitotic cell cycle

The EXP number of annotations for these 3 terms: 

BHF-UCL:  9
PomBase: 3 
SGD: 2
UniProt: 1 (+ 6 ISS)

**Comment by srengel** [comment]
i changed the 2 SGD annotations to negative regulation of cyclin-dependent protein serine/threonine kinase activity GO:0045736 happens_during GO:0000082 G1/S transition of mitotic cell cycle
