### ISSUE TITLE
Announcement: New GO Annotation File Format Coming March 2021

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go_announcements#182]
Dear all,

The GO Consortium would like to announce that, starting with the March 2021 release, we will be updating the format of our GAF (Gene Association File) annotation files.

With the introduction of this new file format, we hope that users will be able to more effectively use GO annotations in their analyses.

The change will be from GAF 2.1 to GAF 2.2 and is:

**GAF 2.2** 

GAF 2.2 now requires a relation for the Qualifier field (column 4).  

Mandatory values in the Qualifier field will allow users to select sets of GO annotations for their analyses based upon the relation between a gene or gene product and a GO term.

The value in the Qualifier field will be a text string that explicitly states the relationship between the gene or gene product annotated in the DB Object ID field (column 2) and the GO ID field (column 5).  

For example:

WBGene00006831 involved_in GO:0008089

All valid relation text strings in the Qualifier field are derived from relations in the [Relations Ontology](https://github.com/oborel/obo-relations).

Negation is still allowed and indicated by prepending and pipe-separating ‘NOT’ from the relation text, e.g., NOT|involved_in.

File specifications for GAF 2.2 can be found on [github](https://github.com/geneontology/geneontology.github.io/blob/issue-go-annotation-2917-gaf-2_2-doc/_docs/go-annotation-file-gaf-format-22.md) and GAF 2.2 files are available on [github](https://github.com/geneontology/go-site/issues/1562#issuecomment-736917271) for testing.

If you have any questions about the GAF 2.2 file format specification, or how to use the new files in your analyses, please [contact us](http://help.geneontology.org/) or email help@geneontology.org.

Thanks,

--Kimberly Van Auken

**Comment by suzialeksander** [comment]
pinning this issue to make it more prominent.
