### ISSUE TITLE
Announcement: Return "-" to partial EC ids for Xrefs in GO ontology

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#184]
Dear all, 

This is to announce that we have restored the EC syntax in the GO cross references, so instead of having for example EC:1 we now have EC:1.-.-.- 

This will ensure that the cross references are compatible with the enzyme website: https://enzyme.expasy.org/EC/1.-.-.-
(whereas https://enzyme.expasy.org/EC/1 does not resolve). 

This will be in the next snapshot and in the next release. 

Thanks, 

Pascale

**Comment by sjm41** [comment]
Woohoo!


==
Steven Marygold
FlyBase
sjm41@cam.ac.uk
