### ISSUE TITLE
Obsoletion notice: Proposal to obsolete GO:0034433 and children

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go_announcements#194]
Dear all, The proposal has been made to obsolete: [(GO:0034433] [Steroid esterificaiton]. The reason for obsoletion is that these terms represent single-step reactions 
There are 35 experimental annotations to this term and/or children

BHF-UCL 13
MGI 1
TAIR 2
UniProt 11
ZFIN 1

There is 1  InterPro2GO mapping to InterPro:IPR030687
This term is included in the 0 subsets
Comments can be made here
https://github.com/geneontology/go-ontology/issues/19255
Annotations are here:
https://docs.google.com/spreadsheets/d/1nvfCX3MejcsA_OuUFH113Xlc8MOpoRB7ZDMpkwuBFkk/edit#gid=0

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on 2/26/2021 Unless objections are received by 2/26/2021,  we will assume that you agree to this change.

**Comment by RLovering** [comment]
UCL annotations all done. Although it is a shame to loose the terms as cholesterol esterification is relevant to human disease and there are multiple human proteins that esterify steroids

**Comment by ValWood** [comment]
hi @RLovering I see 5 sterol/cholesterol  esterases (GO:0004771  
sterol esterase activity) annotated for human, wouldn't these  also all be annotated to some aspect of sterol/ cholesterol metabolism? 

Currently in GO the MF terms do not seem to be specific enough (cholesterol esterase activity is a narrow synonym of sterol esterase and does not have its own term), this won't help to locate them.

**Comment by pgaudet** [comment]
Done https://github.com/geneontology/go-ontology/issues/19255
