### ISSUE TITLE
Announcement: Retirement of legacy services

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go_announcements#202]
We are announcing that as of this Monday, March 8, we will be suspending a few of our long running legacy services and they will no longer be available after that date. These include the legacy services:

SVN
CVS
ext.geneontology.org
viewvc.geneontology.org
FTP

These services have been replaced with GitHub, release.geneontology.org, and other services. 

Please share this information with any tool developers, users, etc. that may still be accessing the legacy services.  For the most up-to-date information on where to access GO data, please see our documentation at http://geneontology.org or ask us for help at https://github.com/geneontology/helpdesk/issues.

**Comment by kltm** [comment]
Noting that archive.geneontology.org, part of the powered-down system, now redirects to release.geneontology.org.
