### ISSUE TITLE
Obsoletion notice: GO:0034649 histone demethylase activity (H3-monomethyl-K4 specific)  and  GO:0034648 histone demethylase activity (H3-dimethyl-K4 specific)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#228]
Dear all, 

The proposal has been made to obsolete 
GO:0034649 histone demethylase activity (H3-monomethyl-K4 specific) 
and 
GO:0034648 histone demethylase activity (H3-dimethyl-K4 specific)

The reason for obsoletion is to align with RHEA and EC: these reactions are sub-reactions of both RHEA and EC. 
These terms have 5 and 13 EXP annotations, respectively. 
GO:0034648 is mapped to RHEA:60216, but this is part of  RHEA:60208, which corresponds to GO:0034647.

Suggestions to move existing annotations are here: https://docs.google.com/spreadsheets/d/1mlEpZji59zgeTQaxan0Ky6hE8B7rEjrrGRg9RpfcatE/edit#gid=0
(note that this requires a GO term created yesterday). 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on July 26, to leave time for groups to make corrections. Unless objections are received by July 26, 2021, we will assume that you agree to this change.

You may comment on the ticket: https://github.com/geneontology/go-ontology/issues/21089
 
Thanks, Pascale

**Comment by ValWood** [comment]
Why not merge into the new term?  It has the same meaning so the annotation should be correct?

**Comment by pgaudet** [comment]
Look at the annotations - we cannot merge, the annotations would be wrong.

**Comment by ValWood** [comment]
OK, i misunderstood. I thought a single new term was replacing 2 terms. I will look closer.
