### ISSUE TITLE
Obsoletion notice: Specific nucleosome disassembly processes

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#251]
Dear all, 
The proposal has been made to obsolete children of ' GO:0006337  nucleosome disassembly' 
* GO:1905783 CENP-A containing nucleosome disassembly
*  GO:0034725 DNA replication-dependent nucleosome disassembly
*  GO:0034726 DNA replication-independent nucleosome disassembly

The reason for obsoletion is that these are no different from the parent class GO:0006337 nucleosome disassembly; DNA replication-dependent nucleosome disassembly and DNA replication-independent nucleosome disassembly specify a phase at which the disassembly takes places; CENP-A containing nucleosome disassembly represents a specific type of nucleosome, but there is no evidence that this is a different process. 

There are no annotations or mappings to these terms; these terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/22133

Thanks, Pascale

**Comment by bmeldal** [comment]
Are you planning to do the same for the assembly terms?

[CPX-3184 EAF5-7-3 nucleosome disassembly/reassembly complex](https://www.ebi.ac.uk/complexportal/complex/CPX-3184)

has both terms, GO:0034725 DNA replication-dependent nucleosome disassembly and GO:0006335 DNA replication-dependent nucleosome assembly.

**Comment by pgaudet** [comment]
HI @bmeldal 

for assembly, we have renamed the terms 'DNA replication-dependent ~nucleosome~ chromatin assembly' (same for independent). 

The idea effect on the nucleosomes is a MF (we have created the term GO:01400713 histone chaperone assembly, and are we will also create 'nucleosome remodeling activity', see #22129), and the nucleosome remodeling activity causes chromatin assembly/disassembly. 

Does that seem reasonable? 

Thanks, Pascale

**Comment by bmeldal** [comment]
I see [GO:0006335 DNA replication-dependent nucleosome assembly](https://www.ebi.ac.uk/QuickGO/term/GO:0006335) in QuickGO. Has it not been updated yet?

In all other aspects, I shall be led by the experts ;-)

**Comment by pgaudet** [comment]
> Has it not been updated yet?


No, I just did that this morning ;)

**Comment by bmeldal** [comment]
Got ya!
