### ISSUE TITLE
Obsoletion notice: GO:0060303 regulation of nucleosome density.

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#283]
Dear all, 

The proposal has been made to obsolete GO:0060303 regulation of nucleosome density. The reason for obsoletion is that this represents a readout and in some cases a phenotype, and the term can be misconstrued for chromatin compaction. 

There are 11 EXP annotations: https://docs.google.com/spreadsheets/d/1HV2nb-8U7b8b9b85pmcCF9m3Uw3z1zMPSTOknPwVLc4/edit#gid=0

1 FlyBase
9 SGD

Suggestions for reannotations have been made, including to a new term 'GO:0140750 nucleosome array spacer activity'. 

There are no mappings; this term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/21503

Thanks, Pascale

**Comment by srengel** [comment]
SGD done.
