### ISSUE TITLE
Obsoletion proposal: GO:0007569 cell aging & regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#295]
Dear all, 

The proposal has been made to obsolete GO:0007569 cell aging & regulation children. The reason for obsoletion is that this represents a phenotype. Some annotations can be moved to the term 'cellular senescence'. 

There are 120 EXP annotations: [GO:0007569 cell aging & regulation children](https://docs.google.com/spreadsheets/d/1FdIe-cpZms1Qsw7wBTF5N8ep59N3wUwoOrXnZaWLLRs/edit#gid=0)

There are no mappings; these terms are not present in any subsets.

Contributor  |  (Assigned by)
--|--
BHF-UCL | 5
CAFA | 1
FlyBase | 2
MGI | 73
RGD | 10
SGD | 7
TAIR | 4
UniProt | 15 - fixed
ZFIN | 3

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/22788

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on February 8th, 2022. Unless objections are received by Feb 8th, we will assume that you agree to this change.

Thanks, Pascale

**Comment by srengel** [comment]
SGD done.
