### ISSUE TITLE
Obsoletion notice: GO:0006928 movement of cell or subcellular component

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#320]
Dear all, 

The proposal has been made to obsolete 
* GO:0006928 movement of cell or subcellular component
and its regulation terms: 
*  GO:0051270 regulation of cellular component movement
*   GO:0051271 negative regulation of cellular component movement
*  GO:0051272 positive regulation of cellular component movement

The reason for obsoletion is that the term mixes cellular and subcellular processes.

- The term 'movement of cell or subcellular component' is in the PIR subset (@hdrabkin can you please let Darren know?) 
- There are 38 EXP annotations (all to regulation terms), see annotations in https://github.com/geneontology/go-annotation/issues/4087
- There are no mappings to these terms. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/19809

Thanks, Pascale

**Comment by nataled** [comment]
I am fine with removing the term from the PIR subset (in general, all deprecated GO terms that happen to be in the PIR subset can be removed from the subset).

**Comment by pgaudet** [comment]
Thanks @nataled
