### ISSUE TITLE
Obsoletion notice: GO:0040035 hermaphrodite genitalia development & GO:0048815 hermaphrodite genitalia morphogenesis

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go_announcements#378]
Dear all, The proposal has been made to obsolete: GO:0040035 hermaphrodite genitalia development & GO:0048815 hermaphrodite genitalia morphogenesis.
The reason for obsoletion is that these terms maybe redundant with female genitalia development and morphogenesis, respectively. 
There are 34 experimental annotations to this term by 
WB 12
Uniprot 22

There are 0 InterPro2GO mappings to this term. 
This term is included in no subset(s).
New annotations should consider more specific anatomical aspects such as vulval development.
Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/23531. 
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on September 19, 2022. Unless objections are received by September 18, 2022, we will assume that you agree to this change.

Thanks.

Raymond

**Comment by raymond91125** [comment]
Annotations are here:
https://docs.google.com/spreadsheets/d/1NOEvv5x5HA2pMDXbIMWPtDVnlvm0v00XHU_w0u1P8H8/edit#gid=0

**Comment by raymond91125** [comment]
@vanaukenk Hi Kimberly, do you need more time to remove the annotations? Thanks.

**Comment by raymond91125** [comment]
@pgaudet Who should be assigned for Uniprot annotations? thanks.

**Comment by pgaudet** [comment]
You can assign @Antonialock

**Comment by Antonialock** [comment]
UniProt fixed (to my best ability!)

**Comment by raymond91125** [comment]
@Antonialock thanks.
