### ISSUE TITLE
Obsoletion notice: GO:0098019 virus tail, major subunit and GO:0098020 virus tail, minor subunit

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#38]
Dear all, 

The proposal has been made to obsolete

GO:0098019 virus tail, major subunit
GO:0098020 virus tail, minor subunit
The reason for obsoletion is that these are not precise structures: major (most abundant) and minor subunits of viral tails vary in different viruses/phages. 

There are no annotations to those terms. There are no mappings; this term is not present in any subsets/slims. Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/16705

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on December 10th, 2018. Unless objections are received by December 10th, 2018.  we will assume that you agree to this change.

Thanks, Pascale

**Comment by paolaroncaglia** [comment]
@pgaudet 
If memory serves me right, those viral terms were part of the viral mapping work carried out by Brenley McIntosh in collaboration with Jane and Becky. See the definition sources (Source: PHI:0000082, GOC:bm). I wasn't involved and can't remember the details, but I think that this publication stemmed from that work: https://www.ncbi.nlm.nih.gov/pubmed/26215368, so you may want to check briefly with at least one of the authors. Of course, if a GO term is published it doesn't mean that it can't be obsoleted, etc. :-)
Thanks,
Paola
