### ISSUE TITLE
Obsoletion GO:0008852 exodeoxyribonuclease I activity and GO:0008853 exodeoxyribonuclease III activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#434]
Dear all, 

The proposal has been made to obsolete  GO:0008852 exodeoxyribonuclease I activity and GO:0008853 exodeoxyribonuclease III activity. The reason for obsoletion is that these terms are equivalent to  GO:0008310 single-stranded DNA 3'-5' exodeoxyribonuclease activity and  GO:0008311 double-stranded DNA 3'-5' exodeoxyribonuclease activity, respectively. 

Mappings to GO:0008852 and GO:0008853 will be moved to GO:0008310 and GO:0008311.

There is EXP annotation to each of these terms by EcoCyc. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24408

Thanks, Pascale

**Comment by pgaudet** [comment]
@amandamackie

**Comment by amandamackie** [comment]
Noted. I will delete/update annotations in EcoCyc shortly

Amanda
