### ISSUE TITLE
Obsoletion notice: [GO:0008219 cell death GO:0070265 necrotic cell death GO:0070267 oncosis]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#464]
Dear all, 

The proposal has been made to obsolete 
GO:0008219 cell death
GO:0070265 necrotic cell death
GO:0070267 oncosis

*  The reason for obsoletion is that this term represent an assay and not a real GO process. 
* The reason for obsoletion is that this represents a phenotype.

Annotations:
There are 110 experimental annotations to this these terms 
cell death 97

| − | (30) | TAIR
| − | (27) | UniProt
| − | (10) | FlyBase
| − | (9) | RGD
| − | (5) | EcoCyc
| − | (5) | MGI
| − | (4) | Xenbase
| − | (2) | CACAO
| − | (2) | dictyBase
| − | (1) | AgBase
| − | (1) | GeneDB
| − | (1) | PseudoCAP

necrotic cell death (12)
| − | (5) | UniProt
| − | (5) | WB
| − | (1) | RGD
| − | (1) | dictyBase

There is 1 InterPro2GO mappings to these term. 

This term is included in the go_slim_agr, goslim_chembl, goslim_drosophila, goslim_mouse  and goslim_plant subset(s). We propose to move these to 'programmed cell death'

Annotations can be viewed here: [https://docs.google.com/spreadsheets/d/1sPkWZ3rNAFpUQRD0d9n2mzi4j7pd8ztBFb33OblWYWw/edit#gid=0].

Annotations can be transferred to  programmed cell death, programmed necrotic cell death or descendants

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/24680
Unless objections are received by 01/02/2023, we will assume that you agree to this change.

Thanks, 

The GO-Ontology Editors

**Comment by pfey03** [comment]
Phenotypes are mostly based on GO in that sense it's not easily separate. I understate necrotic cell death and oncosis but cell death as well is strange

**Comment by ValWood** [comment]
Hi Petra, if you see only cell death, it isn't GO annotatable (it would be just a phenotype). You need to know that it is an  evolved  process in order to make the annotation. Otherwise, I could annotate 1837/5000 genes , where mutants  die under certain conditions, to  cell death.  Cell death should not really have been added to GO. Now it is causing problems because  the function predictors are predicting it from orthologs . It's hard to argue that these annotations   should not exist, because  we have a term and  it has been  used annotation of non-programmed cell death  (i.e. through aging, wear and tear, inability to respond to chemical insults, toxicity, pathological mutation causing toxicity etc)

**Comment by pfey03** [comment]
Will 'autphagic cell death' and the programmed cell death GO stay? I'm done with Dicty

**Comment by ValWood** [comment]
Hi Petra,

All programmed cell death terms will stay in GO. If you look at the annotated graph in https://github.com/geneontology/go-ontology/issues/24680
you can see the terms that will be removed. 
- necrotic cell death will  go because it is a descendent of necrotic cell death and only 'programmed necrotic cell death' terms are required for GO annotation"
- oncosis will go because it is a child of necrotic cell death, but not under programmed cell death.
- cell death will no longer be required as a grouping term because it will be 'single inheritance', (i.e  it will have only one child term "programmed cell death"). This is bad practice in ontology development. It is also causing bad annotation practice, all existing annotations should be 'deeper', or if they are not 'intentional cell death, they should be removed.

There is no problem with autophagic cell death, and it is already positioned correctly under programmed cell death. There are no plans to touch any of the terms under 'programmed cell death' which represents the 'evolved/intentional' cell death pathways.

**Comment by Antonialock** [comment]
uniprot done
