### ISSUE TITLE
Obsoletion notice: GO:0010941 regulation of cell death GO:0060548 negative regulation of cell death GO:0010942 positive regulation of cell death

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#468]
Dear all, 

The proposal has been made to obsolete: 
GO:0010941 regulation of cell death
GO:0060548 negative regulation of cell death
GO:0010942 positive regulation of cell death

These terms are being removed for a combination of reasons:
 The reason for obsoletion is that this term represent an assay and not a GO process.
 The reason for obsoletion is that this represents a phenotype.
 The reason for obsoletion is that this term was added in error.
 The reason for obsoletion is that more specific terms were created.
 The reason for obsoletion is that this term was an unnecessary grouping term.

Annotations:
There are 336  experimental annotations to these terms:

positive regulation of cell death

-- | --

| − | (60) | FlyBase
| − | (35) | RGD
| − | (20) | UniProt
| − | (14) | ARUK-UCL
| − | (9) | TAIR
| − | (6) | BHF-UCL
| − | (4) | ParkinsonsUK-UCL
| − | (3) | ComplexPortal
| − | (2) | AgBase
| − | (2) | MGI
| − | (1) | CACAO
| − | (1) | CAFA
| − | (1) | dictyBase
negative regulation of cell death

-- | -- | -- | --

| − | (49) | RGD
| − | (45) | UniProt
| − | (13) | ComplexPortal
| − | (13) | FlyBase
| − | (11) | MGI
| − | (7) | ParkinsonsUK-UCL
| − | (4) | ARUK-UCL
| − | (3) | BHF-UCL
| − | (3) | TAIR
| − | (2) | ZFIN
| − | (1) | AgBase
regulation of cell death

-- | --

| − | (8) | UniProt
| − | (6) | FlyBase
| − | (5) | TAIR
| − | (4) | MGI
| − | (1) | CAFA
| − | (1) | ParkinsonsUK-UCL
| − | (1) | RGD

There are no mappings to this term.

 This term is not present in any subset.

Annotations can be viewed here: [
](https://docs.google.com/spreadsheets/d/1-NnAiTGTdaRVjMJ7rwtYyMeISicM4upwe9By2sbUIQQ/edit#gid=0)

Annotations can be transferred to  GO:0043067    regulation of programmed cell death  or a descendent if they are part of a cell death pathway. Note that many annotations represent cytotoxic mutations and not evolved cell death pathways, these annotations should be deleted.

Any comments can be  added to the issue: [link to GitHub ticket in the go-ontology tracker]. 
Unless objections are received by  14/02/2023, we will assume that you agree to this change. 

Thanks, 

The GO-Ontology Editors

**Comment by pgaudet** [comment]
Done in https://github.com/geneontology/go-ontology/issues/24755
