### ISSUE TITLE
Obsoletion notice: GO:0042889 3-phenylpropionic acid transport and GO:0042890 3-phenylpropionic acid transmembrane transporter activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go_announcements#475]
Dear all, 

The proposal has been made to obsolete
GO:0042889 3-phenylpropionic acid transport
GO:0042890 3-phenylpropionic acid transmembrane transporter activity

* The reason for obsoletion is that there is no evidence that these function/process exist.

There are no experimental annotations to these terms.

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/21394. 

Thanks, 

The GO-Ontology Editors

**Comment by deustp01** [comment]
Hmm. But what about this RHEA reaction ([RHEA:29747](https://www.rhea-db.org/rhea/29747)), that points to this paper ([PMID: 9603882](https://pubmed.ncbi.nlm.nih.gov/9603882/)) that, from its abstract, appears to be describing exactly such a reaction in E. coli? Sorry for jumping in late.

**Comment by raymond91125** [comment]
Thanks for pointing this out. @pgaudet Should we reverse the pull? I'm not sure how to do it, though.

**Comment by pgaudet** [comment]
@amandamackie said in https://github.com/geneontology/go-ontology/issues/21394#issuecomment-1401112948
that this was predicted, not experimentally characterized. There seems to be no other data than this 1998 paper- see also 
https://www.uniprot.org/uniprotkb/Q47142/entry

We can restore the term when/if we have data. 

Thanks, Pascale

**Comment by raymond91125** [comment]
Closed for now.
