### ISSUE TITLE
Obsoletion notice: histone modifications with "amino acid only" classification (not residue specific) GO:0018024, GO:0035184 , GO:0008469, GO:0035184, GO:1990259,  GO:0035174, GO:0018110 ,  GO:0035400, GO:0140792 GO:0140790 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#479]
Dear all, 

The proposal has been made to obsolete 

GO:0018024   histone lysine N-methyltransferase activity
GO:0035184   histone threonine kinase activity
GO:0008469  histone arginine N-methyltransferase activity
GO:0035184   histone threonine kinase activity
GO:1990259   histone glutamine N-methyltransferase activity

 GO:0035174    histone serine kinase activity
 GO:0018110   histone arginine kinase activity
 GO:0035400  histone tyrosine kinase activity
 GO:0140792 histone tyrosine phosphatase activity
 GO:0140790 histone serine/threonine phosphatase activity

*  The reason for obsoletion is that this term was an unnecessary grouping term.

Annotations:
There are X experimental annotations to this term by (list of impacted groups and their respective numbers of EXP and ISS annotations). 

GO:0018024    histone lysine N-methyltransferase activity & GO:0035184 histone threonine kinase activity
(24) | UniProt
(6) | MGI
(4) | TAIR
(3) | GeneDB
(2) | FlyBase

GO:0008469   histone arginine N-methyltransferase activity
 (6) | UniProt
 (4) | MGI
 (3) | AspGD
 (3) | TAIR
 (2) | CACAO
 (2) | GeneDB
 (2) | HGNC-UCL
 (2) | Reactome
 (1) | WB

GO:0035184    histone threonine kinase activity

(24) | UniProt
(6) | MGI
(4) | TAIR
(3) | GeneDB
(2) | FlyBase

GO:1990259   histone glutamine N-methyltransferase activity
UniProt 2
SGD 1

There are no experimental annotations to these terms.
 GO:0035174    histone serine kinase activity
 GO:0018110   histone arginine kinase activity
 GO:0035400  histone tyrosine kinase activity
 GO:0140792 histone tyrosine phosphatase activity
 GO:0140790 histone serine/threonine phosphatase activity

There are X InterPro2GO/UniRule/UniProtKW mappings to this term. 
.
mappings GO:0008469
UniRule:UR000615760
UniRule:UR000128653

GO:0018024
InterPro:IPR016858
InterPro:IPR006560
InterPro:IPR017155
InterPro:IPR007728
InterPro:IPR013257
InterPro:IPR011381
InterPro:IPR038034
InterPro:IPR043550
InterPro:IPR021654
InterPro:IPR032926
InterPro:IPR045318
InterPro:IPR025789
InterPro:IPR011381
InterPro:IPR038035
InterPro:IPR037841
InterPro:IPR037842
InterPro:IPR018848
InterPro:IPR017111
InterPro:IPR015722
InterPro:IPR025789
InterPro:IPR013110
InterPro:IPR044422
InterPro:IPR025805
InterPro:IPR044420
InterPro:IPR044418
InterPro:IPR044439
InterPro:IPR045318
InterPro:IPR044419
InterPro:IPR016858
InterPro:IPR021162
InterPro:IPR018848
InterPro:IPR007728

UniRule:UR000400130
UniRule:UR000071303

This term is not present in any subset.

Annotations can be viewed here: 
GO:0018024  https://docs.google.com/spreadsheets/d/1gEvtmRnv8x9V-yCBumrvTWgo4rn85tWjfwrzo2shpXc/edit#gid=0
GO:0008469 https://docs.google.com/spreadsheets/d/1pYNPCqeb7xQgb1P5VWEifjnOsMH57eYS0Skn9YRT4Rs/edit#gid=0
GO:0035184  https://docs.google.com/spreadsheets/d/1gEvtmRnv8x9V-yCBumrvTWgo4rn85tWjfwrzo2shpXc/edit#gid=0
GO:1990259 https://docs.google.com/spreadsheets/d/1IAuu_-hDQVMhromMmV5NEoVyGPF7GgxW9LrigSEeM9E/edit#gid=0

If obsolete term has a 'replaced by' term: (optional)
This term is being replaced by [GO term] 

If obsolete term has a 'consider' term:  (optional)
Annotations can be transferred to [suggested GO term(s)] 

Any comments can be  added to the issue: [link to GitHub ticket in the go-ontology tracker]. 
Unless objections are received by [DATE], we will assume that you agree to this change.

Thanks, 

The GO-Ontology Editors

**Comment by pgaudet** [comment]
Done here https://github.com/geneontology/go-ontology/issues/24397
