### ISSUE TITLE
UN-Obsoletion notice: GO:0004239 'methionyl aminopeptidase activity'

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#498]
Dear all, 

The term  GO:0004239 'obsolete methionyl aminopeptidase activity'
was obsoleted 2015-08-26 because it represents a gene product.

However this activity it is a valid specificity for GO  Molecular Function and will be reinstated.

Thanks, 

The GO-Ontology Editors

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/issues/22698
