### ISSUE TITLE
Obsoletion notice:  GO:0006379 mRNA cleavage, GO:0031439 positive regulation of mRNA cleavage, GO:0031437 regulation of mRNA cleavage, GO:0031438 negative regulation of mRNA cleavage, GO:0098787 mRNA cleavage involved in mRNA processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#508]
Dear all, 

The proposal has been made to obsolete Obsoletion request: 
GO:0006379 mRNA cleavage, 
GO:0031439 positive regulation of mRNA cleavage, 
GO:0031437 regulation of mRNA cleavage, 
GO:0031438 negative regulation of mRNA cleavage, 
GO:0098787 mRNA cleavage involved in mRNA processing. 

*  The reason for obsoletion is that this term represents a molecular function.

Annotations:
There are 9 experimental annotations to these terms:

5 GO:0006379 mRNA cleavage
0 GO:0031439 positive regulation of mRNA cleavage
0 GO:0031437 regulation of mRNA cleavage
0 GO:0031438 negative regulation of mRNA cleavage

There are no mappings to this term.

This term is not present in any subset.

If obsolete term has a 'replaced by' term: 

GO:0006379	mRNA cleavage
CONSIDER -> GO:0031124  mRNA 3'-end processing (or another descendant of RNA processing)

GO:0031439	positive regulation of mRNA cleavage
CONSIDER  -> GO:0031442    positive regulation of mRNA 3'-end processing (or another descendant of RNA processing)

GO:0031437	regulation of mRNA cleavage
CONSIDER -> GO:0031440    regulation of mRNA 3'-end processing (or another descendant of RNA processing)

GO:0031438	negative regulation of mRNA cleavage
CONSIDER  -> GO:0031441    negative regulation of mRNA 3'-end processing (or another descendant of RNA processing)

GO:0098787	mRNA cleavage involved in mRNA processing
REPLACE BY -> GO:0031124  mRNA 3'-end processing

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/25185
Unless objections are received by 05-04-23, we will assume that you agree to this change.

Thanks, 

The GO-Ontology Editors

**Comment by srengel** [comment]
SGD done.
