### ISSUE TITLE
Obsoletion notice: GO:0090503 RNA phosphodiester bond hydrolysis, exonucleolytic GO:0090501 RNA phosphodiester bond hydrolysis, endonucleolytic GO:0098789 pre-mRNA cleavage required for polyadenylation GO:0090501 RNA phosphodiester bond hydrolysis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#522]
Dear all, 

The proposal has been made to obsolete 

GO:0090503 RNA phosphodiester bond hydrolysis, exonucleolytic
GO:0090502 RNA phosphodiester bond hydrolysis, endonucleolytic
GO:0098789 pre-mRNA cleavage required for polyadenylation
GO:0090501 RNA phosphodiester bond hydrolysis

* The reason for obsoletion is that the term
These terms represent molecular functions in the process ontology

Annotations:
There are 106 experimental annotations to these terms by (list of impacted groups and their respective numbers of EXP and ISS annotations). 

1 BHF-UCL GO:0090501 RNA phosphodiester bond hydrolysis
2 BHF-UCL GO:0090502 RNA phosphodiester bond hydrolysis, endonucleolytic
4 BHF-UCL GO:0090503 RNA phosphodiester bond hydrolysis, exonucleolytic
7 ComplexPortal GO:0098789 pre-mRNA cleavage required for polyadenylation
2 EcoCyc GO:0090501 RNA phosphodiester bond hydrolysis
2 EcoCyc GO:0090502 RNA phosphodiester bond hydrolysis, endonucleolytic
3 FlyBase GO:0090502 RNA phosphodiester bond hydrolysis, endonucleolytic
2 FlyBase GO:0090503 RNA phosphodiester bond hydrolysis, exonucleolytic
4 GOC GO:0090501 RNA phosphodiester bond hydrolysis
1 GeneDB GO:0098789 pre-mRNA cleavage required for polyadenylation
2 HGNC GO:0090503 RNA phosphodiester bond hydrolysis, exonucleolytic
2 PseudoCAP GO:0090503 RNA phosphodiester bond hydrolysis, exonucleolytic
22 SGD GO:0098789 pre-mRNA cleavage required for polyadenylation
12 UniProt GO:0090501 RNA phosphodiester bond hydrolysis
13 UniProt GO:0090502 RNA phosphodiester bond hydrolysis, endonucleolytic
14 UniProt GO:0090503 RNA phosphodiester bond hydrolysis, exonucleolytic
7 UniProt GO:0098789 pre-mRNA cleavage required for polyadenylation
6 WB GO:0090502 RNA phosphodiester bond hydrolysis, endonucleolytic

 There are no mappings to this term.

 This term is not present in any subset.

Annotations can be viewed here:  https://docs.google.com/spreadsheets/d/1a3Vl6CARGx7UbFGKneTs2m4XqPRAOS39tAq2X-_Zak8/edit#gid=0

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/25259 
Unless objections are received by Friday 5th May, we will assume that you agree to this change.

Thanks, 

The GO-Ontology Editors

**Comment by deustp01** [comment]
> GO:0090501 RNA phosphodiester bond hydrolysis, endonucleolytic

Should be GO:009050**2**?

**Comment by ValWood** [comment]
thanks, fixed
