### ISSUE TITLE
Obsoletion notice: GO:0052063 induction by symbiont of defense-related host nitric oxide production

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#531]
Dear all, 

The proposal has been made to obsolete GO:0052063 induction by symbiont of defense-related host nitric oxide production. The reason for obsoletion is that this process doesn't exist; this represents a host response to a pathogenic symbiont. 

There are no annotations or mappings to this term; this term is not in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/25395

Thanks, Pascale

**Comment by pgaudet** [comment]
This obsoletion also covers  GO:0052028 induction by symbiont of host signal transduction pathway and children:

- GO:0052063 induction by symbiont of defense-related host nitric oxide production. 
-  GO:0052079 induction by symbiont of defense-related host MAP kinase-mediated signal transduction pathway 
- GO:0052072 induction by symbiont of defense-related host salicylic acid-mediated signal transduction pathway
- GO:0043964 induction by symbiont of host adenylate cyclase-mediated signal transduction
- GO:0075134 induction by symbiont of host calcium or calmodulin-mediated signal transduction
- GO:0075209 induction by symbiont of host cAMP-mediated signal transduction
- GO:0052076 induction by symbiont of host ethylene-mediated defense response
- GO:0075131 induction by symbiont of host protein kinase-mediated signal transduction
- GO:0075110 induction by symbiont of host receptor-mediated signal transduction 
-  GO:0075119 induction by symbiont of host G protein-coupled receptor signal transduction

The reason for obsoletion is that these processes do not exist; this represents a host response to a pathogenic symbiont. 

No annotations, no mappings, no subsets.

**Comment by ValWood** [comment]
I'm pretty sure some of these were created for use by PHI-base (you may not see them because their annotation are currently not updating. @jseager7  is looking into this.)

I'm pretty sure there are effectors of necrotrophic fungi which activate host MAP kinase and  NO production to activate the host hypersensitive response (this is usually a host defense mechanism, but the pathogen co-opts it).
 
@jseager7  could you check if PHI-base has any annotations to these terms?

CC @CuzickA

**Comment by ValWood** [comment]
Maybe these processes should be worded differently. There might even be other terms existing that are used for this.

**Comment by pgaudet** [comment]
OK - let me know. 

The idea is to use 'disruption' of signaling pathway rather than induction or suppression, which is a bit misleading. 

You can use a MF 'activator activity' to capture the MAPK activation. Does that work?

**Comment by ValWood** [comment]
The  MF 'activator activity'  but they  still need a process.

Could these obsoleted terms have the "disruption" terms as suggested replacements?

**Comment by jseager7** [comment]
> could you check if PHI-base has any annotations to these terms?

@ValWood PHI-base hasn't made annotations with any of the above GO terms.

**Comment by ValWood** [comment]
OK thanks!
