### ISSUE TITLE
Obsoletion notice: [ASTRA complex GO:0070209]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#592]
Dear all, 

The proposal has been made to obsolete GO:0070209 ASTRA complex  
(keep one, remove others): 

*  The reason for obsoletion is that this term was added in error.
(the complex does not exist)

There are no experimental annotations to this term.
(PomBase and SGD legacy annotations are removed)

There are no mappings to this term.

This term is not present in any subset.

Thanks, 

The GO-Ontology Editors

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/issues/26022
