### ISSUE TITLE
Obsoletion notice: GO:0061912 selective autophagy 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#593]
Dear all, 

The proposal has been made to obsolete GO:0061912 selective autophagy. 

*  The reason for obsoletion is that this term was an unnecessary grouping term.

Annotations:
Annotations will be automatically replaced by GO:0016236  macroautophagy

There are no mappings to this term.

This term is not present in any subset.

If obsolete term has a 'replaced by' term: (optional)
GO:0016236  macroautophagy

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/26115.
Unless objections are received by 22/09/23, we will assume that you agree to this change.

Thanks, 

The GO-Ontology Editors

**Comment by pgaudet** [comment]
I think the hierarchy will be messy without the grouping term, and this will confuse that branch more than needed.

**Comment by ValWood** [comment]
Sorry I went ahead and obsoleted this, as the notice period had expired, and there was a direct replacement.
However I forgot that I needed to create an annotation review ticket even for 'merges' to  inform some groups


+ | − | (22) | DisProt will need to remap from "selective autophagy" to "macroautophagy"
@victorianugnes  can you action this from here?

I won't forget next time.

**Comment by victorianugnes** [comment]
I'm on it, don't worry. I'll need a day or two though, cause there're a lot of annotations with "selective autophagy" and I'll need our dev on this. I'll keep you posted
