### ISSUE TITLE
Obsoletion notice: GO:0030242 autophagy of peroxisome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#600]
Dear all, 

The proposal has been made to obsolete GO:0030242 autophagy of peroxisome

*  The reason for obsoletion is that this term was an unnecessary grouping term.

Annotations:

26 SGD
2 UniProt

There are 2 InterPro2GO/UniRule/UniProtKW mappings to this term. 

InterPro:IPR016347
PIRSF:PIRSF002412 MA_DBI

This term is not present in any subset.

Annotations can be viewed here: https://docs.google.com/spreadsheets/d/1-A9RBBAaYI2IOeZ6YIMmKnJqu64KNFHNGTkWzxVnwpA/edit#gid=0

Annotations can be transferred to [suggested GO term(s)] 
GO:0000426   micropexophagy
or
GO:0000425 pexophagy (which has exact synonym macropexophagy)

Any comments can be  added to the issue: [link to GitHub ticket in the go-ontology tracker]. 
Unless objections are received by 06/10/23, we will assume that you agree to this change.

Thanks, 

The GO-Ontology Editors

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/issues/26190
