### ISSUE TITLE
Obsoletion notice: GO:0005845 mRNA cap binding complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#617]
Dear all, 

The proposal has been made to obsolete GO:0005845 mRNA cap binding complex 

*  The reason for obsoletion is that this term was added in error.

Annotations are here: https://github.com/geneontology/go-annotation/issues/4832

There are 
2 InterPro2GO
1 UniRule
1 HAMAP 
mappings to this term. 

This term is not present in any subset.

If obsolete term has a 'replaced by' term: (optional)
This term is being replaced by 
GO:0034518   RNA cap binding complex

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/26347 

Thanks, 

The GO-Ontology Editors

**Comment by ValWood** [comment]
@esperetta

**Comment by ValWood** [comment]
@blazaropinto

**Comment by ValWood** [comment]
@pgaudet  I can't find who to tag for HAMAP

**Comment by ghost** [comment]
Thank you Val. I have checked and the UniRule (https://www.uniprot.org/unirule/UR000107560) is an HAMAP rule.

**Comment by pgaudet** [comment]
@ValWood you should tag people in the annotation tracker, not here
