### ISSUE TITLE
Obsoletion notice: GO:1902621 actomyosin contractile ring disassembly GO:1990274 mitotic actomyosin contractile ring disassembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#652]
Dear all, 

The proposal has been made to obsolete 

GO:1902621 actomyosin contractile ring disassembly
GO:1990274 mitotic actomyosin contractile ring disassembly
GO:0120151   positive regulation of mitotic actomyosin contractile ring disassembly
GO:0120150 regulation of mitotic actomyosin contractile ring disassembly

*  The reason for obsoletion is that the data from the paper for which the term was requested can be accurately described using:
 GO:0000916 actomyosin contractile ring contraction
 GO:1902404 mitotic actomyosin contractile ring contraction
 GO:1903471 regulation of mitotic actomyosin contractile ring contraction
 GO:1903473 positive regulation of mitotic actomyosin contractile ring contraction

Annotations:
There are 6 experimental annotations to these term by
PomBase 4
SGD 2 

There are no mappings to these term.

These term is not present in any subset.

Annotations can be viewed here:

https://github.com/geneontology/go-annotation/issues/4915

If obsolete term has a 'replaced by' term: (optional)
This term is being replaced by [GO term] (See above list)

Thanks, 

The GO-Ontology Editors

**Comment by pgaudet** [comment]
Ontology ticket completed https://github.com/geneontology/go-ontology/issues/26711
