### ISSUE TITLE
Obsoletion notice: GO:0080009 mRNA methylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#683]
Dear all, 

The proposal has been made to obsolete GO:0080009 mRNA methylation. 

* The reason for obsoletion is that it represents a molecular function

Annotations:
There are 99 experimental annotations to this term by 

1 ARUK-UCL
2 ComplexPortal
14 FlyBase
1 GeneDB
1 MGI
15 SGD
5 TAIR
59 UniProt
1 ZFIN

There are 5 InterPro2GO/UniRule mappings to this term. 

Annotations can be viewed here: https://github.com/geneontology/go-annotation/issues/4981.

If obsolete term has a 'consider' term:  (optional)

I cannot do a 'replace' by or 'consider' because these modifications cover many processes. If you can't locate the term you require, let me know, it is possibly obscure, or does not exist.

Any comments can be added to the issue:  https://github.com/geneontology/go-ontology/issues/26943. 
Unless objections are received by 14/02/24, we will assume that you agree to this change.

Thanks, 

The GO-Ontology Editors

**Comment by sandraorchard** [comment]
Complex Portal done
