### ISSUE TITLE
Obsoletion notice: GO:0006069 ethanol oxidation

### ISSUE THREAD

**Issue by edwong57** [geneontology/go_announcements#710]
Dear all, 

The proposal has been made to obsolete GO:0006069 ethanol oxidation

* The reason for obsoletion is that the term is a molecular function.

Annotations:
There are 10 experimental annotations to this term by

UniProt 6
RGD 3
FlyBase 1

There are no mappings to this term.

This term is not present in any subset.

Annotations can be viewed here: https://github.com/geneontology/go-annotation/issues/5131

Annotations can be transferred to [GO:0019431 acetyl-CoA biosynthetic process from ethanol](https://amigo.geneontology.org/amigo/term/GO:0019431#display-lineage-tab)

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/27260. 
Unless objections are received by Mar 29, we will assume that you agree to this change.

Thanks, 

The GO-Ontology Editors

**Comment by deustp01** [comment]
[Reactome pathway instance](https://reactome.org/content/detail/R-HSA-71384) patched with GO:0006068 'ethanol catabolic process'
