### ISSUE TITLE
Obsoletion notice: GO:0047760 butyrate-CoA ligase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#736]
Dear all, 

The proposal has been made to obsolete GO:0047760 butyrate-CoA ligase activity and replace it by GO:0031956
medium-chain fatty acid-CoA ligase activity. The reason for obsoletion is that butyrate represents a specific substrate. Both terms share the same EC. 

There are 15 EXP annotations, by BHF, RGD (1 each) and UniProt (13), see https://github.com/geneontology/go-annotation/issues/5190 but these will be automatically replaced. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/25800

Thanks, Pascale

**Comment by deustp01** [comment]
Fixed in Reactome (2 instances)

**Comment by pgaudet** [comment]
Sorry @deustp01 ! We still dont have the check for TAS...
