### ISSUE TITLE
Obsoletion notice: GO:0003964 RNA-directed DNA polymerase activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#801]
Dear all, 

The proposal has been made to obsolete GO:0003964 RNA-directed DNA polymerase activity and replace it by its parent, GO:0003720 telomerase activity, because they represent the same activity. 

There are 13 annotations to this term, that will be migrated automatically. There are mappings that need to be fixed: 
interpro2go
reactome2go
uniprotkb_kw2go
unirule2go
hamap2go
See https://github.com/geneontology/go-annotation/issues/5334

This term is not in any subsets. 
You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/28394

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi everyone, 

Sorry I mixed up the terms in the announcement!! 

Indeed the proposal is to obsolete GO:0003721 telomerase RNA reverse transcriptase activity and replace it by GO:0003720 telomerase activity, because they represent the same activity.

Note that we have a small hierarchy of single-children: 
. GO:0003964 RNA-directed DNA polymerase activity
.. GO:0003720 telomerase activity
...  GO:0003721 telomerase RNA reverse transcriptase activity

EC has a single reaction, [EC:2.7.7.49](https://enzyme.expasy.org/EC/2.7.7.49), that represents reverse transcriptase/RNA-directed DNA polymerase activity, that covers TERT, ie telomerase activity. 

We could also merge GO:0003720 telomerase activity up into the parent GO:0003964 RNA-directed DNA polymerase activity to better align with EC (RHEA doesn't have this much specificity, a single RHEA covers 3 ECs: https://www.rhea-db.org/rhea?query=ec%3A2.7.7.49). Currently  GO:0003720 telomerase activity has no cross reference to enzyme databases, generally we'd like to avoid this but of course there may be exceptions. 

Thanks everyone for the feedback ! and sorry for the mix up. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also, obsolete the regulation terms:

 GO:1905661 regulation of telomerase RNA reverse transcriptase activity >> replace by GO:0051972 regulation of telomerase activity: 0 annotations
 GO:1905662 negative regulation of telomerase RNA reverse transcriptase activity >> replace by GO:0051974 negative regulation of telomerase activity: 1 annotation BHF; will be automatically replaced
 GO:1905663 positive regulation of telomerase RNA reverse transcriptase activity >> replace by GO:0051973 positive regulation of telomerase activity: 1 annotation BHF; will be automatically replaced

**Comment by ValWood** [comment]
Shouldn't we also be removing
GO:0051972 regulation of telomerase activity
GO:0051974 negative regulation of telomerase activity
GO:0051973 positive regulation of telomerase activity

from the BP ontology?

**Comment by pgaudet** [comment]
Yes https://github.com/geneontology/go-ontology/issues/28437
