### ISSUE TITLE
Obsoletion notice: GO:0018266 GPI anchor biosynthetic process via N-aspartyl-glycosylphosphatidylinositolethanolamine  and siblings GO:0018267, GO:0018265, GO:0018268, GO:0018269, GO:0018270, GO:0050493

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#808]
Dear all, 

The proposal has been made to obsolete 

GO:0018266 GPI anchor biosynthetic process via N-aspartyl-glycosylphosphatidylinositolethanolamine
GO:0018267 GPI anchor biosynthetic process via N-cysteinyl-glycosylphosphatidylinositolethanolamine
GO:0018265 GPI anchor biosynthetic process via N-asparaginyl-glycosylphosphatidylinositolethanolamine
GO:0018268 GPI anchor biosynthetic process via N-glycyl-glycosylphosphatidylinositolethanolamine
GO:0018269 GPI anchor biosynthetic process via N-seryl-glycosylphosphatidylinositolethanolamine
GO:0018270 GPI anchor biosynthetic process via N-alanyl-glycosylphosphatidylinositolethanolamine
GO:0050493 GPI anchor biosynthetic process via N-threonyl-glycosylphosphatidylinositolethanolamine

 The reason for obsoletion is that these terms represents a molecular functions.

There are no experimental annotations to these terms.

There are no mappings to these terms.

These terms are not present in any subset.

These terms are being replaced by GO:0006506 GPI anchor biosynthetic process

Thanks, 

The GO-Ontology Editors

**Comment by pgaudet** [comment]
Done 
https://github.com/geneontology/go-ontology/issues/28228
