### ISSUE TITLE
Proposal to obsolete GO:0052106 - quorum sensing involved in interaction with host

### ISSUE THREAD

**Issue by krchristie** [geneontology/go_announcements#81]
Dear all,
 
The proposal has been made to obsolete: GO:0052106 - quorum sensing involved in interaction with host. The reason for obsoletion is that the term is not clearly defined and usage has been inconsistent.
There are 33 experimental and 10 ISO annotations to this term by:

BHF-UCL (1 IDA, 1 IMP – both annotations are challenged)
GeneDB (31 IMP, 8 ISO – all IMP ones could be moved to “quorum sensing”)
MGI (1 ISO – depends on challenged annotation)
RGD (1 ISO – depends on challenged annotation)
There are 0 InterPro2GO mappings to this term.

This term is NOT included in any subsets.

This existing term is suggested for transferring annotations that have not been challenged:
-- GO:0009372 – quorum sensing

 
Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/17757 
 
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on October 29th. Unless objections are received by October 28th, we will assume that you agree to this change.
 
Thanks,
 
Karen

**Comment by krchristie** [comment]
@pgaudet - I created this ticket without the label `obsoletion` and I am unable to add a label in this repository.

**Comment by pgaudet** [comment]
> I created this ticket without the label obsoletion and I am unable to add a label in this repository.

Can you try again ? you should have access.

**Comment by krchristie** [comment]
@pgaudet - I've tried again today, but I don't have access. When I mouse over any of the items in the right side bar like `Assignees` or `Labels`, they just stay gray and un-clickanble in this repository. When I do the same thing in the go-ontology or go-annotation repositories, they turn blue and clickable.

**Comment by pgaudet** [comment]
Oh sorry ! I was thinking we were on a different repo. Try again ? (Sorry)

**Comment by krchristie** [comment]
No worries @pgaudet - labels added now to both of my tickets in this repo :)

**Comment by pgaudet** [comment]
Great !!!!
