### ISSUE TITLE
Obsoletion notice: GO:0016254 preassembly of GPI anchor in ER membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go_announcements#835]
Dear all, 

The proposal has been made to obsolete [GO:0016254 preassembly of GPI anchor in ER membrane](https://github.com/geneontology/go-ontology/issues/28227#top)
(keep one, remove others): 

*  The reason for obsoletion is that the data from the paper for which the term was requested can be accurately described using  the parent term GPI anchor biosynthetic process GO:0006506

Annotations:
There are 2 experimental annotations to this term by 

UniProt 2 (Both PigL)

There are no mappings to this term.

This term is not present in any subset.

This term is being replaced by GO:0006506  GPI anchor biosynthetic process

Annotations can be transferred to GO:0006506  GPI anchor biosynthetic process

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/28227. 

Thanks, 

The GO-Ontology Editors

**Comment by deustp01** [comment]
The three Reactome usages have been fixed as recommended - fixes will appear in release next month.
