### ISSUE TITLE
Announcement: Retire gp2protein files

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go_announcements#93]
Dear GO Friends,

The GOC would like to retire the gp2protein files that map gene identifiers from databases, e.g. MGI or WB, to the canonical reference protein in UniProtKB.

These files have been generated by groups contributing annotations to the GOC.

We plan to retire these files in ~ one month's time, February 15th.

We encourage anyone who may still be using these files to contact us (help@geneontology.org) to discuss alternative ways of obtaining these mappings (e.g. gene production information (gpi) files).

You may also comment on the corresponding github ticket:

https://github.com/geneontology/go-site/issues/1324

Thank you.

-- Kimberly Van Auken
-- Pascale Gaudet

**Comment by pgaudet** [comment]
Done.
